# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                XDEBUG: '${XDEBUG}'
                XDEBUG_PORT: '${XDEBUG_PORT}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            PHP_IDE_CONFIG: serverName=Docker
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
#            - redis
#            - meilisearch
#            - selenium
    mysql:
        platform: linux/amd64
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
#    redis:
#        image: 'redis:alpine'
#        ports:
#            - '${FORWARD_REDIS_PORT:-6379}:6379'
#        volumes:
#            - 'sailredis:/data'
#        networks:
#            - sail
#        healthcheck:
#          test: ["CMD", "redis-cli", "ping"]
#          retries: 3
#          timeout: 5s
#    meilisearch:
#        build:
#            context: ./docker/meilisearch
#            dockerfile: Dockerfile
#        ports:
#            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
#        volumes:
#            - 'sailmeilisearch:/data.ms'
#        networks:
#            - sail
#        healthcheck:
#          test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
#          retries: 3
#          timeout: 5s
#    mailhog:
#        image: 'mailhog/mailhog:latest'
#        ports:
#            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
#            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
#        networks:
#            - sail
#    selenium:
#       image: 'selenium/standalone-chrome'
#       volumes:
#            - '/dev/shm:/dev/shm'
#       networks:
#           - sail
#    mongodb:
#        image: mongo
#        container_name: mongodb
#        environment:
#            - PUID=1000
#            - PGID=1000
#        volumes:
#            - 'sailmongo:/data/db'
#        ports:
#            - '${FORWARD_MONGO_DB_PORT:-27017}:27017'
#        restart: unless-stopped
#        networks:
#            - sail
#    mongo-express:
#        image: mongo-express
#        restart: always
#        container_name: mongo-express
#        ports:
#            - 8082:8082
#        environment:
#            - ME_CONFIG_MONGODB_SERVER=mongodb
#            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
#            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#            - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
#            - ME_CONFIG_BASICAUTH_USERNAME=admin
#            - ME_CONFIG_BASICAUTH_PASSWORD=admin123
#        volumes:
#            - 'sailmongo:/data/db'
#        depends_on:
#            - mongodb
#        networks:
#            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
#    sailredis:
#        driver: local
#    sailmeilisearch:
#        driver: local
#    sailmongo:
#        driver: local
